[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
log = "0.4"
pretty_env_logger = "0.5"
thiserror = "1"
vulkanalia = { version = "=0.25.0", features = ["libloading", "provisional", "window"] }
winit = "0.29"